site_name: "ASCT-B Tables"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
docs_dir: docs
nav:
  - Index: index.md
site_url: https://obophenotype.github.io/asctb/
repo_url: https://github.com/obophenotype/asctb/
